-- 1. Añadimos la columna 'locale' a la tabla y cambiamos la clave primaria
ALTER TABLE profile DROP CONSTRAINT IF EXISTS profile_pkey;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS locale varchar(2) DEFAULT 'en';
-- Actualizamos la fila existente a 'en' (si existe) y establecemos la clave primaria combinada
UPDATE profile SET locale = 'en' WHERE locale IS NULL;
ALTER TABLE profile ADD PRIMARY KEY (id, locale);

-- 2. Borramos los datos existentes para reemplazarlos con los 4 idiomas completos
DELETE FROM profile;

-- 3. Insertamos los 4 idiomas (EN, ES, FR, RU)
INSERT INTO profile (id, locale, name, title, tagline, about, contact_email, contact_phone, linkedin_url, skills, experience) VALUES

-- ENGLISH
(1, 'en', 'Fidel Maurín Martínez Jiménez', 'Software Quality Assurance Engineer', 
'Passionate about ensuring quality, efficiency, and reliability in every project through meticulous manual testing and advanced test automation.', 
'With 5 years of experience in the field of code analysis and software testing, I am passionate about ensuring quality and efficiency in every project I participate in. My professional journey has been focused on analysis and testing, where I have honed my ability to identify flaws and develop solutions to enhance user experience.\n\nThroughout my career, I have worked in diverse environments and projects, from web applications to mobile, always striving to overcome challenges and deliver high-quality products. My meticulous approach and attention to detail have allowed me to find effective solutions even in the most complex problems.\n\nI have developed experience in test automation using tools such as Playwright and Cypress. In addition to my technical skills, I value effective communication and teamwork, believing that strong collaboration among development teams, QA, and other stakeholders is essential for project success.', 
'fidelmaurin@gmail.com', '+34 631750906', 'https://www.linkedin.com/in/fidel-maurínmartínez-jiménez', 
'[{"category": "Quality Assurance", "items": ["Test Automation", "Manual & API Testing", "Regression & E2E Testing", "Agile (SCRUM)"]}, {"category": "Automation Tools", "items": ["Playwright", "Cypress", "Selenium", "Postman"]}, {"category": "Tech & Dev", "items": ["Python", "Java", "CI/CD Pipelines", "Jira & Confluence"]}, {"category": "Languages", "items": ["Spanish (Native)", "English (Native/Bilingual)", "French (Native/Bilingual)", "Italian, Japanese, Russian"]}]', 
'[{"date": "March 2025 - Present", "role": "QA Tester", "company": "Sales Pipe Pro", "description": "Development and maintenance of automated tests using Python, Pytest, and Playwright for Odoo CRM processes. Integration of automated tests into CI/CD pipelines."}, {"date": "Feb 2024 - Feb 2025", "role": "Software Testing Engineer", "company": "SopraSteria", "description": "UI test automation using Cypress and Selenium. Design, execution, and maintenance of test cases across Agile environments."}, {"date": "Jul 2022 - Jul 2023", "role": "Software Testing Engineer", "company": "Werfen", "description": "Execution of tests, regression testing, exploratory testing, and software risk analysis. Working with C++, VS, Agile frameworks."}, {"date": "Apr 2019 - Jul 2022", "role": "QA", "company": "Softdevel", "description": "Manual and API testing using Python and Postman. UI automation exposure and test documentation maintenance."}]'),

-- SPANISH
(1, 'es', 'Fidel Maurín Martínez Jiménez', 'Ingeniero de Calidad de Software (QA)', 
'Apasionado por asegurar la calidad, eficiencia y fiabilidad en cada proyecto a través de pruebas manuales meticulosas y automatización avanzada.', 
'Con 5 años de experiencia en el análisis de código y pruebas de software, me apasiona garantizar la calidad y eficiencia en cada proyecto en el que participo. Mi trayectoria profesional se ha centrado en el análisis y testing, donde he perfeccionado mi habilidad para identificar fallos y desarrollar soluciones que mejoren la experiencia del usuario.\n\nA lo largo de mi carrera, he trabajado en diversos entornos y proyectos, desde aplicaciones web hasta móviles, siempre esforzándome por superar desafíos y entregar productos de alta calidad. Mi enfoque meticuloso y atención al detalle me han permitido encontrar soluciones efectivas incluso en los problemas más complejos.\n\nHe desarrollado experiencia en automatización de pruebas usando herramientas como Playwright y Cypress. Además de mis habilidades técnicas, valoro la comunicación efectiva y el trabajo en equipo, creyendo firmemente que una sólida colaboración entre los equipos de desarrollo, QA y otras partes interesadas es esencial para el éxito de cualquier proyecto.', 
'fidelmaurin@gmail.com', '+34 631750906', 'https://www.linkedin.com/in/fidel-maurínmartínez-jiménez', 
'[{"category": "Control de Calidad", "items": ["Automatización de Pruebas", "Pruebas Manuales y API", "Pruebas de Regresión y E2E", "Metodologías Ágiles (SCRUM)"]}, {"category": "Herramientas de Automatización", "items": ["Playwright", "Cypress", "Selenium", "Postman"]}, {"category": "Tecnología y Desarrollo", "items": ["Python", "Java", "Pipelines CI/CD", "Jira y Confluence"]}, {"category": "Idiomas", "items": ["Español (Nativo)", "Inglés (Bilingüe)", "Francés (Bilingüe)", "Italiano, Japonés, Ruso"]}]', 
'[{"date": "Marzo 2025 - Presente", "role": "QA Tester", "company": "Sales Pipe Pro", "description": "Desarrollo y mantenimiento de pruebas automatizadas con Python, Pytest y Playwright para procesos de CRM Odoo. Integración en pipelines CI/CD."}, {"date": "Feb 2024 - Feb 2025", "role": "Ingeniero de Pruebas de Software", "company": "SopraSteria", "description": "Automatización de pruebas de interfaz de usuario (UI) usando Cypress y Selenium. Diseño, ejecución y mantenimiento de casos de prueba en entornos Agile."}, {"date": "Jul 2022 - Jul 2023", "role": "Ingeniero de Pruebas de Software", "company": "Werfen", "description": "Ejecución de pruebas, pruebas de regresión, pruebas exploratorias y análisis de riesgos de software. Trabajo con C++, VS, frameworks Agile."}, {"date": "Abr 2019 - Jul 2022", "role": "Analista QA", "company": "Softdevel", "description": "Pruebas manuales y de API usando Python y Postman. Exposición inicial a automatización UI y mantenimiento de documentación de pruebas."}]'),

-- FRENCH
(1, 'fr', 'Fidel Maurín Martínez Jiménez', 'Ingénieur en Assurance Qualité Logicielle (QA)', 
'Passionné par la garantie de la qualité, de l''efficacité et de la fiabilité dans chaque projet grâce à des tests manuels méticuleux et une automatisation avancée.', 
'Avec 5 ans d''expérience dans l''analyse de code et les tests de logiciels, je suis passionné par l''assurance qualité et l''efficacité dans chaque projet auquel je participe. Mon parcours professionnel s''est concentré sur l''analyse et les tests, où j''ai perfectionné ma capacité à identifier les failles et à développer des solutions pour améliorer l''expérience utilisateur.\n\nTout au long de ma carrière, j''ai travaillé dans divers environnements et projets, des applications web aux applications mobiles, en m''efforçant toujours de relever des défis et de livrer des produits de haute qualité. Mon approche méticuleuse et mon souci du détail m''ont permis de trouver des solutions efficaces même aux problèmes les plus complexes.\n\nJ''ai développé une expertise dans l''automatisation des tests en utilisant des outils tels que Playwright et Cypress. Outre mes compétences techniques, j''accorde une grande importance à la communication efficace et au travail d''équipe, convaincu qu''une forte collaboration entre les développeurs, la QA et les autres parties prenantes est essentielle au succès d''un projet.', 
'fidelmaurin@gmail.com', '+34 631750906', 'https://www.linkedin.com/in/fidel-maurínmartínez-jiménez', 
'[{"category": "Assurance Qualité", "items": ["Automatisation des tests", "Tests manuels et API", "Tests de régression et E2E", "Méthodologie Agile (SCRUM)"]}, {"category": "Outils d''Automatisation", "items": ["Playwright", "Cypress", "Selenium", "Postman"]}, {"category": "Technologies et Dév", "items": ["Python", "Java", "Pipelines CI/CD", "Jira et Confluence"]}, {"category": "Langues", "items": ["Espagnol (Maternel)", "Anglais (Bilingue)", "Français (Bilingue)", "Italien, Japonais, Russe"]}]', 
'[{"date": "Mars 2025 - Présent", "role": "Testeur QA", "company": "Sales Pipe Pro", "description": "Développement et maintenance de tests automatisés avec Python, Pytest et Playwright pour les processus CRM Odoo. Intégration CI/CD."}, {"date": "Fév 2024 - Fév 2025", "role": "Ingénieur Test Logiciel", "company": "SopraSteria", "description": "Automatisation des tests UI via Cypress et Selenium. Conception et exécution de cas de test en environnements Agile."}, {"date": "Juil 2022 - Juil 2023", "role": "Ingénieur Test Logiciel", "company": "Werfen", "description": "Exécution de tests, tests de régression, tests exploratoires et analyse des risques. Environnement C++, VS et Agile."}, {"date": "Avr 2019 - Juil 2022", "role": "Analyste QA", "company": "Softdevel", "description": "Tests manuels et API (Python/Postman). Initiation à l''automatisation UI et gestion de la documentation."}]'),

-- RUSSIAN
(1, 'ru', 'Фидель Маурин Мартинес Хименес', 'Инженер по обеспечению качества программного обеспечения', 
'Стремлюсь обеспечить качество, эффективность и надежность каждого проекта посредством тщательного ручного тестирования и передовой автоматизации.', 
'Обладая 5-летним опытом в области анализа кода и тестирования программного обеспечения, я с энтузиазмом отношусь к обеспечению качества и эффективности каждого проекта. Мой профессиональный путь был сосредоточен на анализе и тестировании, где я отточил свое умение выявлять недостатки и разрабатывать решения для улучшения пользовательского опыта.\n\nНа протяжении своей карьеры я работал в различных средах и проектах, от веб- до мобильных приложений, всегда стремясь преодолевать трудности и поставлять высококачественные продукты. Тщательный подход и внимание к деталям позволили мне находить эффективные решения даже для самых сложных проблем.\n\nУ меня есть опыт автоматизации тестирования с использованием таких инструментов, как Playwright и Cypress. Помимо технических навыков, я ценю эффективное общение и командную работу, считая, что тесное сотрудничество между командами разработки, QA и другими заинтересованными сторонами имеет важное значение для успеха проекта.', 
'fidelmaurin@gmail.com', '+34 631750906', 'https://www.linkedin.com/in/fidel-maurínmartínez-jiménez', 
'[{"category": "Контроль качества", "items": ["Автоматизация тестирования", "Ручное и API тестирование", "Регрессионное и E2E тестирование", "Agile (SCRUM)"]}, {"category": "Инструменты автоматизации", "items": ["Playwright", "Cypress", "Selenium", "Postman"]}, {"category": "Технологии", "items": ["Python", "Java", "CI/CD", "Jira & Confluence"]}, {"category": "Языки", "items": ["Испанский (Родной)", "Английский (Свободный)", "Французский (Свободный)", "Итальянский, Японский, Русский"]}]', 
'[{"date": "Март 2025 - Настоящее время", "role": "QA Тестировщик", "company": "Sales Pipe Pro", "description": "Разработка и поддержка автоматизированных тестов с использованием Python, Pytest и Playwright для CRM Odoo."}, {"date": "Фев 2024 - Фев 2025", "role": "Инженер по тестированию ПО", "company": "SopraSteria", "description": "Автоматизация UI-тестов с помощью Cypress и Selenium. Разработка и выполнение тестовых сценариев."}, {"date": "Июль 2022 - Июль 2023", "role": "Инженер по тестированию ПО", "company": "Werfen", "description": "Регрессионное, исследовательское тестирование и анализ рисков ПО. Работа с C++, VS, Agile."}, {"date": "Апр 2019 - Июль 2022", "role": "QA Специалист", "company": "Softdevel", "description": "Ручное и API тестирование (Python, Postman). Базовые навыки UI автоматизации."}]');
